env:
  AZURE_LOGICAPPBE_PACKAGE_PATH: '\'

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@master

    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_MSFT_CREDENTIALS }}

    - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: 'build logicapp-be'
      shell: pwsh
      run: |
        pushd './${{ env.AZURE_LOGICAPPBE_PACKAGE_PATH }}'
        dotnet build --configuration Release --output ./output
        popd

    - name: 'deploy logic-app-be'
      uses: Azure/functions-action@v1
      id: logic-app-be
      with:
        app-name: ${{github.event.inputs.LogicAppBEName}}
        package: '${{ env.AZURE_LOGICAPPBE_PACKAGE_PATH }}/output'
